### PR TITLE
feat: ask user for `enableSecurelyPassphraseCache`

### PR DESCRIPTION
**Pull request by AnnAngela**
This pr includes these changes:
* Implement the popup feature described at https://github.com/wdhongtw/vscode-gpg-indicator/pull/48#issuecomment-1462304729;
* Rename `indicator` folder to `backend` to indicate that the codes in this folder should not be coupled with vscode api;
* Move other codes to `frontend` folder to reduce the size of `extension.ts`;
* Abstracte the `ObjectStorage` class to provide consistent interfaces;
* Modify `.vscodeignore` to reflect the changes from #49.

### CODE REVIEW

**Comment by AnnAngela** [comment]
@wdhongtw Hi, sorry for pinging. Does this issue have any problem?

**Comment by wdhongtw** [comment]
@AnnAngela I'll start review these days. sorry for the late response.

**Comment by wdhongtw** [comment]
Hi @AnnAngela , this PR looks great to me. Especially `AbstractObjectStorage`, I realy likes that. :D

As the change of project structure..  I would like to keep structure of `./src` and `./src/indicator` untouched.
Could you change it back? :D

**Comment by AnnAngela** [comment]
@wdhongtw No problem.

And I would like to discuss the required vscode version, if we can update to vscode v1.74, we can use built-in [`LogOutputChannel`](https://code.visualstudio.com/api/references/vscode-api#LogOutputChannel) so we don't need to make a logger by ourself. This `LogOutputChannel` follow the developer log level setting, and has ability to popup up the panel ([`LogOutputChannel#show`](https://code.visualstudio.com/api/references/vscode-api#LogOutputChannel.show)) when we need to show error detail to user.

You can try it yourself by using these codes, then when debugging in extension debugger host, play the `global.outputChannel` in debug console of the original vscode window:
```typescript
// we need to disable ts type check for `global`
// @ts-ignore
global.outputChannel = vscode.window.createOutputChannel('GPG Indicator test', { log: true });
```

image

Even further, if we can update to v1.75, we can avoid the warning message for `activationEvents` in package.json.

image

The only con I can think of is that we would lose the users who don't updating their vscode or using forked version like [cloud studio](https://cloudstudio.net/). What do you think?

**Comment by AnnAngela** [comment]
And one of the pro for using `LogOutputChannel` is that the `LogOutputChannel` can be used like `console`, it can output object and error directly, like this:

image

It seems to run `JSON.stringify` on the object passed in, but not a big problem.

**Comment by wdhongtw** [comment]
> if we can update to vscode v1.74, we can use built-in ...

> Even further, if we can update to v1.75 ...

I think six-months is a reasonable choice for backward compatibility.
So for logger interface, we can set engine version to v1.74 around May 2023, and to v1.75 around June 2023.

We can create GitHub issue beforehand if you want this to be tracked. :D

@AnnAngela

**Comment by wdhongtw** [comment]
I noticed another force-push today <https://github.com/wdhongtw/vscode-gpg-indicator/compare/61b63fb7120042e6122604ab265752b9eb5d0e72..66dfa9e205bf82f943a395aa9559d874a371f36f> . Thanks for the self-review. :D

---

Passphrase-cache feature should be ready now (I think?).
I will update contributor list and make next release these days, maybe in early April. :D

**Comment by AnnAngela** [comment]
> > if we can update to vscode v1.74, we can use built-in ...
> 
> > Even further, if we can update to v1.75 ...
> 
> I think six-months is a reasonable choice for backward compatibility.
> So for logger interface, we can set engine version to v1.74 around May 2023, and to v1.75 around June 2023.
> 
> We can create GitHub issue beforehand if you want this to be tracked. :D
> 
> @AnnAngela
> 
> 

Your idea is great, let's track it in the new issue.

<hr>

> I noticed another force-push today <https://github.com/wdhongtw/vscode-gpg-indicator/compare/61b63fb7120042e6122604ab265752b9eb5d0e72..66dfa9e205bf82f943a395aa9559d874a371f36f> . Thanks for the self-review. :D
> 
> ---
> 
> Passphrase-cache feature should be ready now (I think?).
> I will update contributor list and make next release these days, maybe in early April. :D

I think so, thanks for your review!

**Pull request merged**
