### PR TITLE
Use secret storage API to remember passphrase

### PR DESCRIPTION
**Pull request by AnnAngela**
As https://github.com/wdhongtw/vscode-gpg-indicator/issues/25 I tried to use secret storage API to remember passphrase, and I update the dependencies and tsconfig for easier development. @wdhongtw

### CODE REVIEW

**Comment by wdhongtw** [comment]
Hi @AnnAngela , thanks for the PR, but I think there are some issue to be resolve.

## Option for not keeping passphrase cache in VS Code.

The most important one is that this PR causing a breaking change to user. Users with updated package will all keep a copy of passphrase in VSCode secret engine. Considering different security requirement of environment (or user preference), it may not be a good idea to turn on this passphrase memorization for all user.

I thought there are two possible way to provide this feature.

- Provide seperate VS Code Commands for user to set / clear passphrase, and load the passphrase on key-unlock action.
- Provide a prompt to ask user whether to memorize the passphrase in VS Code, and remember the action selected by user.

## Passphrase for different key / folder

Currently the extention solve multi-key / multi-folder by selecting the key associated with focused file. (see `onDidChangeActiveTextEditor` and `onDidChangeWorkspaceFolders`). So there are some situation that there should be multiple memorized passphrases, and chosing the right one with current active key.

I have another extension which already did similar things, see [implementation](https://github.com/wdhongtw/vscode-otp-toolbox/blob/main/src/extension.ts) if your are interested.

## Misc.

I thought it would be better if the chore job adjustment (linter configuration, dependency update, VS Code target...) can be extract into another PR.

---

Again, thanks for the PR, this is what I want but I takes no action for long time. :D

**Comment by AnnAngela** [comment]
THX for your feedback, I will make these changes tomorrow:
1. Separate the chore job adjustment to another PR;
2. Add an option (default `false`) to enable / disable the passphrase cache;
3. Use the `git.user.singingKey` as prefix or suffix for passphrase cache key;
4. When the focused file or the `git.user.singingKey`(#40) changes, regenerate new cache key and reload it;
5. Add a command to set / unset the cached passphrase;
6. Show the hash and associated email in the passphrase prompt.

**Comment by AnnAngela** [comment]
There is a problem: I don't know how to get the associated email of a key ...

**Comment by wdhongtw** [comment]
Maybe parsing output from `gpg -k --with-colons <key-id>`?

**Pull request closed without merging**
